# wrangler.toml
name = 'cloudflare'
main = "src/index.ts"
compatibility_date = "2024-10-23"
compatibility_flags = [ "nodejs_compat" ]
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true




# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
